name: Balances Depuracao

on:
  schedule:
    - cron: '*/1 * * * *'  # Executa a cada 1 minuto
  workflow_dispatch:        # Mantém a execução manual

# Adiciona controle de concorrência
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  run-balances:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary pandas pygsheets

      - name: Setup Google Credentials
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > controles.json

      - name: Run balances script
        run: |
          set -x  # Mostra os comandos sendo executados
          echo "=== Iniciando execução em $(date) ==="
          python -u balances_depuração.py  # Flag -u força output sem buffer
          echo "=== Finalizado em $(date) ==="
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          GOOGLE_SHEETS_CREDS: 'controles.json'