name: Balances Depuracao

on:
  schedule:
    - cron: '*/1 * * * *'  # Executa a cada 1 minuto
  workflow_dispatch:        # Mantém a execução manual

# Adiciona controle de concorrência com nome único
concurrency:
  group: balances-depuracao-${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  run-balances:
    runs-on: ubuntu-latest
    # Removendo environment: production para evitar conflito
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary pandas pygsheets pytz

      - name: Setup Google Credentials
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > controles_balances.json  # Nome diferente do arquivo

      - name: Run balances script
        run: |
          set -x  # Mostra os comandos sendo executados
          echo "=== Iniciando execução em $(date) ==="
          import pygsheets
          import os
          gc = pygsheets.authorize(service_file=os.getenv('GOOGLE_SHEETS_CREDS', 'controles_balances.json'))
          GOOGLE_SHEETS_CREDS=controles_balances.json python -u balances_depuração.py
          echo "=== Finalizado em $(date) ==="
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          GOOGLE_SHEETS_CREDS: 'controles_balances.json'

      - name: Cleanup
        if: always()
        run: |
          rm -f controles_balances.json