name: Balances Depuracao

on:
  push:
    branches: [ main ]  # Adiciona trigger de push na branch main
  schedule:
    - cron: '*/60 * * * *'  # Roda a cada hora para manter o job ativo
  workflow_dispatch:    # Mantém a execução manual

# Adiciona controle de concorrência com nome único
concurrency:
  group: balances-depuracao-${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  run-balances:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary pandas pygsheets pytz

      - name: Setup Google Credentials
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > controles.json

      - name: Run balances script in background
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          GOOGLE_SHEETS_CREDS: 'controles.json'
        run: |
          nohup python balances_depuração.py > balances.log 2>&1 &
          echo "Script iniciado em background"
          # Mantém o job rodando por ~55 minutos
          sleep 3300

      - name: Upload log file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: balances-log
          path: balances.log

      - name: Cleanup
        if: always()
        run: |
          rm -f controles.json