name: Indicadores Daily Balance

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/1 * * * *'  # Roda a cada 1 minuto, igual ao balances
  workflow_dispatch:

concurrency:
  group: indicadores-${{ github.workflow }}
  cancel-in-progress: false  # Não cancela jobs em andamento, igual ao balances

permissions:
  contents: read

jobs:
  update-indicadores:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary pandas pygsheets pytz

      - name: Setup Google Credentials
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > controles.json

      - name: Executar atualização dos indicadores em background
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          GOOGLE_SHEETS_CREDS: 'controles.json'
        run: |
          python -u indicadores_dailybalance.py &  # Roda em background
          echo "Script iniciado em background"
          sleep 3300  # Mantém rodando por 55 minutos

      - name: Cleanup
        if: always()
        run: |
          rm -f controles.json