name: Indicadores Daily Balance

on:
  schedule:
    # A cada 5 minutos durante horário comercial em dias úteis
    - cron: '*/5 9-18 * * 1-5'
    # A cada 15 minutos fora do horário comercial em dias úteis
    - cron: '*/15 0-8,19-23 * * 1-5'
    # A cada 30 minutos nos finais de semana
    - cron: '*/30 * * * 0,6'
  workflow_dispatch: # Permite execução manual

jobs:
  update-indicadores:
    runs-on: ubuntu-latest
    timeout-minutes: 4  # Limita execução a 4 minutos para evitar sobreposição
    environment: production

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary pandas pygsheets pytz

      - name: Executar atualização dos indicadores
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python indicadores_dailybalance.py